# Ce dossier est utilisé pour afficher ce projet sur mon site web (https://smartineau.me)
# This folder is used to display this project on my website (https://smartineau.me)
description = "Un CLI pour facilement créer vos propres CLI"
etiquettes = [ "js", "npm" ]
url_site_web = "https://www.npmjs.com/package/create-custom-command"
contenu = "./article.md"
date_de_creation = 2020-06-22T00:33:53.691Z
